version: 2

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - unused        # Check for unused code
    - govet         # Vet examines Go source code
    - staticcheck   # Advanced Go linter (includes gosimple)
    - gocritic      # Opinionated linter
    - revive        # Fast linter
    - gosec         # Security issues
    - misspell      # Spell check
    - copyloopvar   # Go 1.22+ loop variable semantics
  disable-all: false

formatters:
  enable:
    - gofmt         # Check code formatting
    - goimports     # Check import formatting

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true

  goimports:
    local-prefixes: github.com/victorzhuk/go-ent

  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - deprecatedComment
      - dupImport
      - elseif
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - typeAssertChain
      - unlambda
      - unslice

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
